expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('server.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)    
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

server/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, logout_then_login
from django.contrib.auth.decorators import login_required

from . import views
from .views import add_report, DeleteReport, list_report, list_account, list_category, UpdateReport, registration

#app_name = 'server'
urlpatterns = [
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/registration/', views.registration, name='registration'),
    path('', login_required(views.BASE), name='BASE'),
    
    path('add_report/', login_required(views.add_report), name = 'add_report'),

    path('list_report/', login_required(views.list_report), name = 'list_report'),
    path('list_account/', login_required(views.list_account), name = 'list_account'),
    path('list_category/', login_required(views.list_category), name = 'list_category'),

    path('update_report/<int:pk>', login_required(UpdateReport.as_view()), name = 'update_report'),


    path('delete_report/<int:pk>', login_required(DeleteReport.as_view()), name = 'delete_report'),


    path('chart/', login_required(views.chart_category), name='chart_category'),
    path('ajax/load-categories/', login_required(views.load_categories), name = 'ajax_load_categories'),

    path('logout/', logout_then_login, name = 'logout')
]

server/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.shortcuts import redirect

class Account(models.Model):
    name = models.CharField(max_length=50)
    budget = models.FloatField()

    def __str__(self):
        return self.name

class Category(models.Model):
    account = models.ForeignKey(Account, on_delete=models.PROTECT)
    name = models.CharField(max_length=50)
    budget = models.FloatField()

    def __str__(self):
        return self.name

class Method(models.Model):
    name = models.CharField(max_length=50)
        
    def __str__(self):
        return self.name

class Report(models.Model):
    #profile = models.ForeignKey(User, on_delete=models.CASCADE)    
    date = models.DateField(default=timezone.now)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.FloatField(default=0)
    payment = models.ForeignKey(Method, on_delete=models.CASCADE)
    description = models.CharField(max_length= 50, default='')
    
    def __str__(self):
        return self.description + ' | ' + str(self.date)

    def get_absolute_url(self):
        return redirect('/')
    
    class Meta:
        ordering = ('id',)

server/forms.py
from django import forms
from .models import Report, Account, Category
from bootstrap_datepicker_plus.widgets import DatePickerInput

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = '__all__'

        widgets = {
            #'profile': forms.Select(attrs={'class': 'form-control'}),
            'date': forms.DateInput(attrs={'class': 'form-control'}),
            'account': forms.Select(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'price': forms.TextInput(attrs={'class': 'form-control'}),
            'payment': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            }
            
    def __init__(self, *args, **kargs):
        super().__init__(*args, **kargs)

        self.fields['category'].queryset = Account.objects.none() #hace que no salga ninguna opción en category

        if 'account' in self.data:
            try:
                account_id = int(self.data.get('account'))
                self.fields['category'].queryset = Category.objects.filter(account_id = account_id).order_by('name')
            except (ValueError, TypeError):
                pass

        elif self.instance.pk:
            self.fields['category'].queryset = self.instance.account.category_set.order_by('name')

class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = '__all__'

        widgets = {
            #'profile': forms.Select(attrs={'class': 'form-control'}),
            'name': forms.DateInput(attrs={'class': 'form-control'}),
            }
      

server/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView, UpdateView
from .models import Report, Category, Account
from .forms import ReportForm
import plotly.express as px
from django.db.models import Sum
from django.contrib.auth.forms import UserCreationForm

def registration(request):
    form = UserCreationForm()
    context = {'form': form}
    return render(request, 'registration/registration.html', context)

def BASE(request):
    reports = Report.objects.all()
    return render(request, 'index.html', {'reports': reports})


def list_report(request):
    reports = Report.objects.all()
    return render(request, 'list.html', {'reports': reports})

def list_account(request):
    accounts = Account.objects.all()
    return render(request, 'list_account.html', {'accounts': accounts})

def list_category(request):
    categories = Category.objects.all()
    return render(request, 'list_category.html', {'categories': categories})


class UpdateReport(UpdateView):
    model = Report
    template_name = 'add_report.html'
    form_class = ReportForm
    success_url = reverse_lazy('list_report')

class UpdateAccount(UpdateView):
    model = Report
    template_name = 'add_account.html'
    form_class = ReportForm
    success_url = reverse_lazy('list_account')

class UpdateCategory(UpdateView):
    model = Category
    template_name = 'add_category.html'
    form_class = ReportForm
    success_url = reverse_lazy('list_account')


class DeleteReport(DeleteView):
    model = Report
    success_url = reverse_lazy('list_report')

class DeleteAccount(DeleteView):
    model = Account
    success_url = reverse_lazy('list_account')

class DeleteCategory(DeleteView):
    model = Category
    success_url = reverse_lazy('list_category')


def add_report(request):
    form = ReportForm()
    if request.method == 'POST':
        form = ReportForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('list_report')
    return render(request, 'add_report.html', {'form': form})

def chart_category(request):
    sums = Report.objects.values('category__name').annotate(total_price=Sum('price'))
    fig = px.pie(sums, values='total_price', names='category__name')
    chart = fig.to_html()
    context = {'chart_category': chart}
    return render(request, 'chart.html', context)

def load_categories(request):
    account_id = request.GET.get('account_id')
    categories = Category.objects.filter(account_id=account_id).all()
    return render(request, 'category_dropdown_list_options.html', {'categories': categories})

server/templates/add_account.html
{% extends 'basee.html' %}

{% block title %}
Add Account
{% endblock %}

{% block content %}

<h1>Add Account</h1>
<br/>
<div>
    <form method="post" id="accountform" data-categories-url="{% url 'ajax_load_categories' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary">Add</button>
    </form>
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> 
    <script>
        $("#id_account").change(function () {
            const url = $("#reportform").attr("data-categories-url");
            const accountId = $(this).val();
            console.log('este es el account id');
            console.log(accountId);
            $.ajax({
                url: url,
                data: {
                    'account_id': accountId    
                },
                success: function (data) {
                    
                    $("#id_category").html(data);    
                }
            });
        });
                
    </script>
</div>

{% endblock %}

server/templates/add_category.html
{% extends 'basee.html' %}

{% block title %}
Add Account
{% endblock %}

{% block content %}

<h1>Add Account</h1>
<br/>
<div>
    <form method="post" id="accountform" data-categories-url="{% url 'ajax_load_categories' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary">Add</button>
    </form>
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> 
    <script>
        $("#id_account").change(function () {
            const url = $("#reportform").attr("data-categories-url");
            const accountId = $(this).val();
            console.log('este es el account id');
            console.log(accountId);
            $.ajax({
                url: url,
                data: {
                    'account_id': accountId    
                },
                success: function (data) {
                    
                    $("#id_category").html(data);    
                }
            });
        });
                
    </script>
</div>

{% endblock %}

server/templates/add_report.html
{% extends 'basee.html' %}

{% block title %}
Add report
{% endblock %}

{% block content %}

<h1>Add Report</h1>
<br/>
<div>
    <form method="post" id="reportform" data-categories-url="{% url 'ajax_load_categories' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary">Add</button>
    </form>
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> 
    <script>
        $("#id_account").change(function () {
            const url = $("#reportform").attr("data-categories-url");
            const accountId = $(this).val();
            console.log('este es el account id');
            console.log(accountId);
            $.ajax({
                url: url,
                data: {
                    'account_id': accountId    
                },
                success: function (data) {
                    
                    $("#id_category").html(data);    
                }
            });
        });
                
    </script>
</div>

{% endblock %}

server/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            Expenses Report
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'BASE' %}">Expenses report</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'add_report' %}">Add Report</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Charts
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">By date</a></li>
                  <li><a class="dropdown-item" href="#">By account</a></li>
                  <li><a class="dropdown-item" href="{% url 'chart_category' %}">By category</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    <br/>
    <div class='container'>
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

server/templates/category_dropdown_list_options.html
<option value="">---------</option>
{% for category in categories %}
<option value="{{ category.pk }}">{{ category.name }}</option>
{% endfor %}

server/templates/chart.html
{% extends 'base.html' %}

{% block content %}
    <h1>Reports</h1>
{{ chart_category|safe }} <!-- aca podria hacer un condicional dependiendo del chart que quiera -->
    <a href="{% url 'logout' %}" class="btn btn-secondary" >Log out</a>
    
{% endblock %}

server/templates/detail.html
{% extends 'base.html' %}
{% block title %}
Detail view
{% endblock %}
{% block content %}
{% endblock %}

server/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Hi {{user.username}}, here are your reports</h1>
    <ul>
    {% for report in object_list %}

        <li>{{report.date}} | {{report.category}} | {{report.price}} <br/>
            {{report.description}} </li>
            <br/>

    {% endfor %}
    </ul>
    <a href="{% url 'logout' %}" class="btn btn-secondary" >Log out</a>
    
{% endblock %}

server/templates/list.html
{% extends 'basee.html' %}

{% block title %}
Add report
{% endblock %}

{% block content %}


<div class="orders">
    <div class="row">
        <div class="col-xl-9">
            <div class="card">
                <div class="card-body">
                    <h4 class="box-title">Reports <a href="{% url 'add_report' %}"><button type="button" class="btn btn-success">+</button></a></h4>
                </div>
                <div class="card-body--">
                    <div class="table-stats order-table ov-h">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>DATE</th>
                                    <th>ACCOUNT</th>
                                    <th>CATEGORY</th>
                                    <th>PRICE</th>
                                    <th>PAYMENT METHOD</th>
                                    <th>DESCRIPTION</th>
                                    <th>OPTIONS</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for report in reports %}
                                <tr>
                                    <td>{{ report.id }}</td>
                                    <td>{{ report.date }}</td>
                                    <td>{{ report.account }}</td>
                                    <td>{{ report.category }}</td>
                                    <td>{{ report.price }}</td>
                                    <td>{{ report.payment }}</td>
                                    <td>{{ report.description }}</td>
                                    <td><a href="{% url 'update_report' report.id %}"><button type="button" class="btn btn-info">Update</button></a></td>
                                    <td><a href="{% url 'delete_report' report.id %}"><button type="button" class="btn btn-danger">Delete</button></a></td>
                                </tr>   
                                {% endfor %}
                                </tbody>
                        </table>
                    </div> <!-- /.table-stats -->
                </div>
            </div> <!-- /.card -->
    </div>
</div>
<!-- /.orders -->

{% endblock %}

server/templates/list_account.html
{% extends 'basee.html' %}

{% block title %}
Add Account
{% endblock %}

{% block content %}


<div class="orders">
    <div class="row">
        <div class="col-xl-7">
            <div class="card">
                <div class="card-body">
                    <h4 class="box-title">Accounts  <button type="button" class="btn btn-success">+</button></h4>
                </div>
                <div class="card-body--">
                    <div class="table-stats order-table ov-h">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>NAME</th>
                                    <th>OPTIONS</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for account in accounts %}
                                <tr>
                                    <td>{{ account.id }}</td>
                                    <td>{{ account.name }}</td>
                                    <td><button type="button" class="btn btn-info">Update</button></td>
                                    <td><button type="button" class="btn btn-danger">Delete</button></td>
                                </tr>   
                                {% endfor %}
                                </tbody>
                        </table>
                    </div> <!-- /.table-stats -->
                </div>
            </div> <!-- /.card -->
    </div>
</div>
<!-- /.orders -->

{% endblock %}

server/templates/list_category.html
{% extends 'basee.html' %}

{% block title %}
Add Category
{% endblock %}

{% block content %}


<div class="orders">
    <div class="row">
        <div class="col-xl-9">
            <div class="card">
                <div class="card-body">
                    <h4 class="box-title">Categories  <button type="button" class="btn btn-success">+</button> </h4>
                </div>
                <div class="card-body--">
                    <div class="table-stats order-table ov-h">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>NAME</th>
                                    <th>ACCOUNT</th>
                                    <th>OPTIONS</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for category in categories %}
                                <tr>
                                    <td>{{ category.id }}</td>
                                    <td>{{ category.name }}</td>
                                    <td>{{ category.account }}</td>
                                    <td><button type="button" class="btn btn-info">Update</button></td>
                                    <td><button type="button" class="btn btn-danger">Delete</button></td>
                                </tr>   
                                {% endfor %}
                                </tbody>
                        </table>
                    </div> <!-- /.table-stats -->
                </div>
            </div> <!-- /.card -->
    </div>
</div>
<!-- /.orders -->

{% endblock %}

server/templates/server/report_confirm_delete.html
{% extends 'basee.html' %}
{% block title %}
Delete report
{% endblock %}
{% block content %}


<h1>Delete Report</h1>
<br/>
<div>
    <form method="post">
        {% csrf_token %}
        <strong>Are you sure you want to delete report # {{ object.id }}?</strong><br/><br/>
        <td><button type="submit" class="btn btn-danger">Delete</button></td>
    </form>
    
</div>

{% endblock %}

templates/index.html
{% extends 'basee.html' %}

{% block title %}
Add report
{% endblock %}

{% block content %}
                <!-- /Widgets -->
                <!--  Traffic  -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="box-title">Traffic </h4>
                            </div>
                            <div class="row">
                                <div class="col-lg-8">
                                    <div class="card-body">
                                        <!-- <canvas id="TrafficChart"></canvas>   -->
                                        <div id="traffic-chart" class="traffic-chart"></div>
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="card-body">
                                        <div class="progress-box progress-1">
                                            <h4 class="por-title">Visits</h4>
                                            <div class="por-txt">96,930 Users (40%)</div>
                                            <div class="progress mb-2" style="height: 5px;">
                                                <div class="progress-bar bg-flat-color-1" role="progressbar" style="width: 40%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                                            </div>
                                        </div>
                                        <div class="progress-box progress-2">
                                            <h4 class="por-title">Bounce Rate</h4>
                                            <div class="por-txt">3,220 Users (24%)</div>
                                            <div class="progress mb-2" style="height: 5px;">
                                                <div class="progress-bar bg-flat-color-2" role="progressbar" style="width: 24%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                                            </div>
                                        </div>
                                        <div class="progress-box progress-2">
                                            <h4 class="por-title">Unique Visitors</h4>
                                            <div class="por-txt">29,658 Users (60%)</div>
                                            <div class="progress mb-2" style="height: 5px;">
                                                <div class="progress-bar bg-flat-color-3" role="progressbar" style="width: 60%;" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                                            </div>
                                        </div>
                                        <div class="progress-box progress-2">
                                            <h4 class="por-title">Targeted  Visitors</h4>
                                            <div class="por-txt">99,658 Users (90%)</div>
                                            <div class="progress mb-2" style="height: 5px;">
                                                <div class="progress-bar bg-flat-color-4" role="progressbar" style="width: 90%;" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
                                            </div>
                                        </div>
                                    </div> <!-- /.card-body -->
                                </div>
                            </div> <!-- /.row -->
                            <div class="card-body"></div>
                        </div>
                    </div><!-- /# column -->
                </div>
                <!--  /Traffic -->
                <div class="clearfix"></div>
                <!-- Orders -->
                <div class="orders">
                    <div class="row">
                        <div class="col-xl-8">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="box-title">Reports </h4>
                                </div>
                                <div class="card-body--">
                                    <div class="table-stats order-table ov-h">
                                        <table class="table ">
                                            <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>DATE</th>
                                                    <th>ACCOUNT</th>
                                                    <th>CATEGORY</th>
                                                    <th>PRICE</th>
                                                    <th>PAYMENT METHOD</th>
                                                    <th>DESCRIPTION</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for report in reports %}
                                                <tr>
                                                    <td><a href="{% url 'update_report' report.id %}">{{ report.id }}</a></td>
                                                    <td>{{ report.date }}</td>
                                                    <td>{{ report.account }}</td>
                                                    <td>{{ report.category }}</td>
                                                    <td>{{ report.price }}</td>
                                                    <td>{{ report.payment }}</td>
                                                    <td>{{ report.description }}</td>
                                                </tr>   
                                                {% endfor %}
                                                </tbody>
                                        </table>
                                    </div> <!-- /.table-stats -->
                                </div>
                            </div> <!-- /.card -->
                        </div>  <!-- /.col-lg-8 -->

                        <div class="col-xl-4">
                            <div class="row">
                                <div class="col-lg-6 col-xl-12">
                                    <div class="card br-0">
                                        <div class="card-body">
                                            <div class="chart-container ov-h">
                                                <div id="flotPie1" class="float-chart"></div>
                                            </div>
                                        </div>
                                    </div><!-- /.card -->
                                </div>

                                <div class="col-lg-6 col-xl-12">
                                    <div class="card bg-flat-color-3  ">
                                        <div class="card-body">
                                            <h4 class="card-title m-0  white-color ">August 2018</h4>
                                        </div>
                                         <div class="card-body">
                                             <div id="flotLine5" class="flot-line"></div>
                                         </div>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- /.col-md-4 -->
                    </div>
                </div>
                <!-- /.orders -->
            <!-- Calender Chart Weather  -->
                <div class="row">
          

                    <div class="col-lg-4 col-md-6">
                        <div class="card ov-h">
                            <div class="card-body bg-flat-color-2">
                                <div id="flotBarChart" class="float-chart ml-4 mr-4"></div>
                            </div>
                            <div id="cellPaiChart" class="float-chart"></div>
                        </div><!-- /.card -->
                    </div>

                </div>
                <!-- /Calender Chart Weather -->
            </div>
        </div>
        <!-- /.content -->
        <div class="clearfix"></div>
        <!-- Footer -->
        <footer class="site-footer">
            <div class="footer-inner bg-white">
                <div class="row">
                    <div class="col-sm-6">
                        Copyright &copy; 2018 Ela Admin
                    </div>
                    <div class="col-sm-6 text-right">
                        Designed by <a href="https://colorlib.com">Colorlib</a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- /.site-footer -->
    </div>
    <!-- /#right-panel -->
    {% endblock %}